### ISSUE TITLE
Container position = absolute

### ISSUE THREAD

**Issue by Zaporozhec7** [malaman/js-image-zoom#11]
Why container position made "absolute" ([On this line](https://github.com/malaman/js-image-zoom/blob/master/package/js-image-zoom.js#L148))? It make hard to make layout. Is there are exists necessity in this? For positioning "relative" should be fine. I have tried replace to "relative" and it works fine

**Comment by malaman** [comment]
Hi,
i will check possible side-effects of changing container position style from `absolute` to `relative`.

**Comment by Zaporozhec7** [comment]
Thank you very much

**Comment by malaman** [comment]
I've published 0.4.1 version on npm with `position: relative` for container.
