### ISSUE TITLE
Images with spaces in URLs can't be used for ImageZoom

### ISSUE THREAD

**Issue by matejsvajger** [malaman/js-image-zoom#12]
https://github.com/malaman/js-image-zoom/blob/9957ca8e9ebef45db814b70c182ce24006aa04e1/package/js-image-zoom.js#L164

This line will fail setting a background image on images that contain spaces or `(` `)` in their url.

I would suggest wrapping the value into quotes:
`"url('" + data.sourceImg.element.src + "')";`

**Comment by malaman** [comment]
Hi. Thanks for reporting this. I will wrap values into quotes within next minor release.

**Comment by malaman** [comment]
Fixed in 0.6.0 version.
