### ISSUE TITLE
undefined is not an object (evaluating 'this.imageZoom.kill')

### ISSUE THREAD

**Issue by pkumar01** [malaman/js-image-zoom#16]
I am getting below issue tracked in error reporting, could you please tell me what am i missing with my implementation.

I am using version 0.7.0

undefined is not an object (evaluating 'l.sourceImg.element.onload=p')
undefined is not an object (evaluating 'this.imageZoom.kill')

**Comment by malaman** [comment]
Could you post an example, which reproduce the issue?

**Comment by pkumar01** [comment]
Sorry can't, i also tried reproducing it but couldn't, these error i can only see in my error reports of my production application.

Let me any pointers to debug or fix this.

**Comment by malaman** [comment]
Please post used arguments for your application and affected browser versions.
