### ISSUE TITLE
the best way to update the image 

### ISSUE THREAD

**Issue by badrshs** [malaman/js-image-zoom#21]
Hey  , I was trying to update the image by re-calling the method again 
            var imageZoom = new ImageZoom(document.getElementById("img-container"), options);
but seems like this solution  is not good , any better way to do that please ?

**Comment by malaman** [comment]
Hi,
check the [Demo](http://malaman.github.io/js-image-zoom/example/) -> see "change image" button
The code ist here: https://github.com/malaman/js-image-zoom/blob/master/example/index.html#L196
This is currently the only supported way.

**Comment by relh** [comment]
I found that updating the image-zoom like this doesn't work when there are two image-zooms on the same image.

**Comment by relh** [comment]
I saw this just closed, but incase it's useful to anyone, I did something slightly related that was tricky.

I made two image zooms on the same image and also wanted to be able to update the underlying picture. To get it to work I had to use the method of assigning the zoom to an existing div and then manually triggering the onMouseMove events for each of them. 

You can see it halfway down the page here:
https://relh.github.io/sun_site/
https://github.com/relh/sun_site/blob/main/index.html
https://github.com/relh/sun_site/blob/main/main.js

Big thanks to malaman for this great tool!
