### ISSUE TITLE
image zoom package is not installing

### ISSUE THREAD

**Issue by diggu13** [malaman/js-image-zoom#33]
I am unable to install the zoom image in Powershell in js file
![Screenshot 2021-11-22 123344](https://user-images.githubusercontent.com/94375210/142818095-ff521c1d-992d-46d1-9af8-68e2112baad4.png)

**Comment by malaman** [comment]
Hi, 
error message says, that `npm` is not installed or not in `PATH` on your system.
Maybe this helps: [SO Answer](https://stackoverflow.com/a/21923238)
