### ISSUE TITLE
Flickering On Initial Roll

### ISSUE THREAD

**Issue by brand-services** [malaman/js-image-zoom#35]
Solid plugin...

On initial hover, I am noticing the js-image-zoom__zoomed-image is switching from display:block to display:none, causing a flickering.

This does not happen after rolling off and back on. Any thoughts?

Also the img param, was under the assumption this was to be the zoom image to be loaded on init, given many users may not hover ever.

**Comment by brand-services** [comment]
looks like its from loading the plugin dynamically, but still can't solve why the  js-image-zoom__zoomed-image erratically goes from block to none

**Comment by theRealPadster** [comment]
I am having this issue as well. What was your solution @brand-services ?

**Comment by theRealPadster** [comment]
Fixed it on my end. For anyone seeing this in the future: 

It looks like adding `zoomLensStyle: 'z-index: 1;'` fixes it. 
Or with css:
```css
.js-image-zoom__zoomed-area {
  z-index: 1;
}
```
